/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accueil;

import client.EspaceClient;
import connectionProvider.ConnectionProvider;
import doctor.DiagnosticPatient;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import patient.AjouterNouveauPatient;
import patient.Gestion_RV;
import doctor.DiagnosticPatient;
import patient.HistoriqueCompletDuPatient;
import pharmacie.Facturation;
import pharmacie.Pharmacie;

/**
 *
 * @author issaga.gaye
 */
public class Accueil extends javax.swing.JFrame {
    int nbTentative = 0;
    /**
     * Creates new form Login
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jbtnLongin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jtypeUser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBtnHistoricComm = new javax.swing.JButton();
        jBtnEspaceAgent = new javax.swing.JButton();
        jBtnEspaceClient = new javax.swing.JButton();
        jBtnHelp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnRV = new javax.swing.JButton();
        jBtnDignosticPatient = new javax.swing.JButton();
        jBtnAjouterPatient = new javax.swing.JButton();
        jBtnFacturation = new javax.swing.JButton();
        jBtnHistoric = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Nom d'utilisateur");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jtxtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Mot de passe");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 210, 40));

        jbtnLongin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnLongin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Se_Connecter.jpg"))); // NOI18N
        jbtnLongin.setText("Se connecter");
        jbtnLongin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLonginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLongin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_1.png"))); // NOI18N
        jbtnExit.setText("Quitter");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jbtnCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCancel.setText("Annuler");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jtypeUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtypeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docteur", "Agent", "Patient/Client", " " }));
        jPanel1.add(jtypeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 65, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Type d'utilisateur");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 640, 340));

        jBtnHistoricComm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnHistoricComm.setText("Historique Commande");
        jBtnHistoricComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHistoricCommActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnHistoricComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 300, 60));

        jBtnEspaceAgent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEspaceAgent.setText("Espace Agent");
        jBtnEspaceAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEspaceAgentActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEspaceAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 330, 60));

        jBtnEspaceClient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEspaceClient.setText("Acheter une Ordonance");
        jBtnEspaceClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEspaceClientActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEspaceClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, 60));

        jBtnHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnHelp.setText("Aide");
        getContentPane().add(jBtnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 330, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Système de gestion de pharmacie");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 640, 60));

        jBtnRV.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnRV.setText("Rendez-vous");
        jBtnRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRVActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnRV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 330, 60));

        jBtnDignosticPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDignosticPatient.setText("Diagnostic Patient");
        jBtnDignosticPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDignosticPatientActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDignosticPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 330, 60));

        jBtnAjouterPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnAjouterPatient.setText("Ajouter Patient");
        jBtnAjouterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjouterPatientActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAjouterPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 330, 60));

        jBtnFacturation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnFacturation.setText("Facturation");
        jBtnFacturation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFacturationActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnFacturation, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 300, 60));

        jBtnHistoric.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnHistoric.setText("Historique Patient");
        jBtnHistoric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHistoricActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnHistoric, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 300, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acc.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1350, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       jBtnHistoricComm.setEnabled(false);
       jBtnAjouterPatient.setEnabled(false);
       jBtnHelp.setEnabled(false);
       jBtnDignosticPatient.setEnabled(false);
       jBtnEspaceClient.setEnabled(false);
       jBtnRV.setEnabled(false);
       jBtnAjouterPatient.setEnabled(false);
       jBtnEspaceAgent.setEnabled(false);
       jBtnFacturation.setEnabled(false);
       jBtnHistoric.setEnabled(false);
       
    }//GEN-LAST:event_formWindowActivated
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirmez si vous voulez quitter", "Système de gestion de pharmacie", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        jtxtUsername.setText("");
        jPassword.setText("");
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnLonginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLonginActionPerformed
        String username = jtxtUsername.getText();
        String password = jPassword.getText();
        
        
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select * from inscription  where username='"+username+"' AND password='"+password+"'");
            if(rs.next()){
                jBtnHistoric.setEnabled(true);
                jBtnHistoricComm.setEnabled(true);
                if(jtypeUser.getSelectedItem().equals("Agent") || jtypeUser.getSelectedItem().equals("Doctor")){
                    jBtnHistoricComm.setEnabled(true);
                    jBtnHelp.setEnabled(true);
                    jBtnEspaceAgent.setEnabled(true);
                    jBtnAjouterPatient.setEnabled(true);
                    jBtnFacturation.setEnabled(true);
                    jBtnRV.setEnabled(true);
                    
                    jBtnEspaceClient.setEnabled(true);
                    
       
                    
                }
                
                else if(jtypeUser.getSelectedItem().equals("Patient/Client")){
                    jBtnHelp.setEnabled(true);
                    jBtnEspaceClient.setEnabled(true);
                    
                    jBtnRV.setEnabled(true);
                    jBtnAjouterPatient.setEnabled(false);
                    jBtnRV.setEnabled(true);
                    
                    jBtnEspaceAgent.setEnabled(false);               
                    
            }
                else{
                    jBtnHelp.setEnabled(true);
                    jBtnEspaceAgent.setEnabled(true);
                    jBtnAjouterPatient.setEnabled(true);
                    jBtnRV.setEnabled(true);
                    
                    jBtnFacturation.setEnabled(true);
                    jBtnEspaceClient.setEnabled(true);
                    
                    jBtnDignosticPatient.setEnabled(true);
                }
                
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Utilisateur ou mot de passe incorrect.");
                jBtnHelp.setEnabled(false);
                
                jBtnEspaceClient.setEnabled(false);
                
                jBtnEspaceAgent.setEnabled(false);
                nbTentative +=1;
                if(nbTentative==3){
                    System.exit(0);
                }
            }
                      
        }
        catch(Exception e){ 
            JOptionPane.showMessageDialog(null, "Utilisateur ou mot de passe incorrect");
            
        }
        
        
    }//GEN-LAST:event_jbtnLonginActionPerformed

    private void jBtnEspaceAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEspaceAgentActionPerformed
        Pharmacie monPharmacie = new Pharmacie();
        monPharmacie.setVisible(true);
    }//GEN-LAST:event_jBtnEspaceAgentActionPerformed

    private void jBtnEspaceClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEspaceClientActionPerformed

        EspaceClient commande = new EspaceClient();
        commande.setVisible(true);
    }//GEN-LAST:event_jBtnEspaceClientActionPerformed

    private void jBtnRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRVActionPerformed
        Gestion_RV rv = new Gestion_RV();
        rv.setVisible(true);
               
    }//GEN-LAST:event_jBtnRVActionPerformed

    private void jBtnDignosticPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDignosticPatientActionPerformed
        DiagnosticPatient dcp = new DiagnosticPatient();
        dcp.setVisible(true);
    }//GEN-LAST:event_jBtnDignosticPatientActionPerformed

    private void jBtnFacturationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFacturationActionPerformed
        Facturation fact = new Facturation();
        fact.setVisible(true);
    }//GEN-LAST:event_jBtnFacturationActionPerformed

    private void jBtnAjouterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjouterPatientActionPerformed
        AjouterNouveauPatient ajouterPatient = new AjouterNouveauPatient();
        ajouterPatient.setVisible(true);
    }//GEN-LAST:event_jBtnAjouterPatientActionPerformed

    private void jBtnHistoricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHistoricActionPerformed
        HistoriqueCompletDuPatient historic = new HistoriqueCompletDuPatient();
        historic.setVisible(true);
    }//GEN-LAST:event_jBtnHistoricActionPerformed

    private void jBtnHistoricCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHistoricCommActionPerformed
        DiagnosticPatient diagnostic = new DiagnosticPatient();
        diagnostic.setVisible(true);
    }//GEN-LAST:event_jBtnHistoricCommActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAjouterPatient;
    private javax.swing.JButton jBtnDignosticPatient;
    private javax.swing.JButton jBtnEspaceAgent;
    private javax.swing.JButton jBtnEspaceClient;
    private javax.swing.JButton jBtnFacturation;
    private javax.swing.JButton jBtnHelp;
    private javax.swing.JButton jBtnHistoric;
    private javax.swing.JButton jBtnHistoricComm;
    private javax.swing.JButton jBtnRV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLongin;
    private javax.swing.JTextField jtxtUsername;
    private javax.swing.JComboBox<String> jtypeUser;
    // End of variables declaration//GEN-END:variables
}
