/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pharmacie.Pharmacie;

/**
 *
 * @author issaga.gaye
 */
public class Login extends javax.swing.JFrame {
    int nbTentative = 0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jbtnLongin = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jBtnDoctor = new javax.swing.JButton();
        jBtnPharmacy = new javax.swing.JButton();
        jBtnPayment = new javax.swing.JButton();
        jBtnPatient = new javax.swing.JButton();
        jBtnPharmacyOffice = new javax.swing.JButton();
        jBtnGP_Apointment = new javax.swing.JButton();
        jBtnHospital = new javax.swing.JButton();
        jBtnSurgery = new javax.swing.JButton();
        jBtnConsultant = new javax.swing.JButton();
        jBtnSpecialist = new javax.swing.JButton();
        jBtnHelp = new javax.swing.JButton();
        jBtnPharmacist = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Nom d'utilisateur");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jtxtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Mot de passe");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 210, 40));

        jbtnLongin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnLongin.setText("Se connecter");
        jbtnLongin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLonginActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLongin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Quitter");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jbtnCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCancel.setText("Annuler");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 680, 340));

        jBtnDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDoctor.setText("Docteur");
        jBtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 60));

        jBtnPharmacy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPharmacy.setText("Pharmacie");
        jBtnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPharmacyActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, 60));

        jBtnPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPayment.setText("Paiement");
        getContentPane().add(jBtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 260, 60));

        jBtnPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPatient.setText("Patient");
        getContentPane().add(jBtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 260, 60));

        jBtnPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPharmacyOffice.setText("Cabinet Pharmacie");
        jBtnPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPharmacyOfficeActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 60));

        jBtnGP_Apointment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnGP_Apointment.setText("Rendez-vous");
        getContentPane().add(jBtnGP_Apointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 260, 60));

        jBtnHospital.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnHospital.setText("Hopital");
        getContentPane().add(jBtnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 160, 200, 60));

        jBtnSurgery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSurgery.setText("Opération");
        getContentPane().add(jBtnSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 90, 200, 60));

        jBtnConsultant.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnConsultant.setText("Consultant");
        getContentPane().add(jBtnConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 310, 200, 60));

        jBtnSpecialist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSpecialist.setText("Specialiste");
        getContentPane().add(jBtnSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 240, 200, 60));

        jBtnHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnHelp.setText("Aide");
        getContentPane().add(jBtnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 460, 200, 60));

        jBtnPharmacist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnPharmacist.setText("Pharmaciste");
        getContentPane().add(jBtnPharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 390, 200, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Système de gestion de pharmacie");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 4, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 760, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPharmacyOfficeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPharmacyOfficeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       jBtnDoctor.setEnabled(false);
       jBtnConsultant.setEnabled(false);
       jBtnGP_Apointment.setEnabled(false);
       jBtnHelp.setEnabled(false);
       jBtnHospital.setEnabled(false);
       jBtnPatient.setEnabled(false);
       jBtnPayment.setEnabled(false);
       jBtnPharmacist.setEnabled(false);
       jBtnPharmacy.setEnabled(false);
       jBtnPharmacyOffice.setEnabled(false);
       jBtnSpecialist.setEnabled(false);
       jBtnSurgery.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jBtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDoctorActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirmez si vous voulez quitter", "Système de gestion de pharmacie", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        jtxtUsername.setText("");
        jPassword.setText("");
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnLonginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLonginActionPerformed
        String username = jtxtUsername.getText();
        String password = jPassword.getText();
        
        if(username.contains("awa") && password.contains("awa")){
            
            jtxtUsername.setText("");
            jPassword.setText("");
            
            jBtnDoctor.setEnabled(true);
            jBtnConsultant.setEnabled(true);
            jBtnGP_Apointment.setEnabled(true);
            jBtnHelp.setEnabled(true);
            jBtnHospital.setEnabled(true);
            jBtnPatient.setEnabled(true);
            jBtnPayment.setEnabled(true);
            jBtnPharmacist.setEnabled(true);
            jBtnPharmacy.setEnabled(true);
            jBtnPharmacyOffice.setEnabled(true);
            jBtnSpecialist.setEnabled(true);
            jBtnSurgery.setEnabled(true);
        }
        
        else if(!(username.contains("awa") && password.contains("awa"))){
            jtxtUsername.setText("");
            jPassword.setText("");
            
            jBtnDoctor.setEnabled(false);
            jBtnConsultant.setEnabled(false);
            jBtnGP_Apointment.setEnabled(false);
            jBtnHelp.setEnabled(false);
            jBtnHospital.setEnabled(false);
            jBtnPatient.setEnabled(false);
            jBtnPayment.setEnabled(false);
            jBtnPharmacist.setEnabled(false);
            jBtnPharmacy.setEnabled(false);
            jBtnPharmacyOffice.setEnabled(false);
            jBtnSpecialist.setEnabled(false);
            jBtnSurgery.setEnabled(false);
            
            nbTentative +=1;
            if(nbTentative==3){
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jbtnLonginActionPerformed

    private void jBtnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPharmacyActionPerformed
        Pharmacie monPharmacie = new Pharmacie();
        monPharmacie.setVisible(true);
    }//GEN-LAST:event_jBtnPharmacyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConsultant;
    private javax.swing.JButton jBtnDoctor;
    private javax.swing.JButton jBtnGP_Apointment;
    private javax.swing.JButton jBtnHelp;
    private javax.swing.JButton jBtnHospital;
    private javax.swing.JButton jBtnPatient;
    private javax.swing.JButton jBtnPayment;
    private javax.swing.JButton jBtnPharmacist;
    private javax.swing.JButton jBtnPharmacy;
    private javax.swing.JButton jBtnPharmacyOffice;
    private javax.swing.JButton jBtnSpecialist;
    private javax.swing.JButton jBtnSurgery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLongin;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
