package pharmacie;

import connectionProvider.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import patient.AjouterNouveauPatient;

/**
 *
 * @author issaga.gaye
 */
public class Pharmacie extends javax.swing.JFrame {

    int q, i, id, deletItem;
    /**
     * Creates new form Pharmacie
     */
    public Pharmacie() {
        initComponents();
        AfficherTableaux();
    }
    
    public void AfficherTableaux(){
        //DefaultTableModel model = new DefaultTableModel();
       
       try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select * from medicament ");
            //jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
            //model.addRow(new Object[]{rs});
        }
        catch(Exception e){ 
            JOptionPane.showMessageDialog(null, "Erreur de connexion");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtLot = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtIssueDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtDateExp = new javax.swing.JTextField();
        jtxtDoseJour = new javax.swing.JLabel();
        jtxtDoseDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtpossibleSideEffets = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtCompInfo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtStrorageAdvice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtNotice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnAjouter = new javax.swing.JButton();
        jBtnModifier = new javax.swing.JButton();
        jBtnSuprimer = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jNbrTablette = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcmbNomTable = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Numero Ref:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jtxtRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 210, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Nom Tablette:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Dose (mg):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Lot:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jtxtLot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Date fabrik");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jtxtIssueDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Date d'exp");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jtxtDateExp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtDateExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 210, -1));

        jtxtDoseJour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDoseJour.setText("Dose par jour");
        getContentPane().add(jtxtDoseJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jtxtDoseDay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtDoseDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("effet secondaire possible");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        jtxtpossibleSideEffets.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtpossibleSideEffets, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("infos complémentaires");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jtxtCompInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtCompInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, 210, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("conseil de stockage");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        jtxtStrorageAdvice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtStrorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Notice");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        jtxtNotice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jtxtNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, 210, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1350, 330));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnAjouter.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnAjouter.setText("Ajouter");
        jBtnAjouter.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBtnAjouterComponentShown(evt);
            }
        });
        jBtnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 40));

        jBtnModifier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnModifier.setText("Modifier");
        jBtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModifierActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 160, 40));

        jBtnSuprimer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSuprimer.setText("Suprimer");
        jBtnSuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSuprimerActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSuprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 160, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Quitter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1330, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Nombre de Tablette");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jNbrTablette.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jNbrTablette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNbrTabletteActionPerformed(evt);
            }
        });
        getContentPane().add(jNbrTablette, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 180, 210, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Stock");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, -1));

        jcmbNomTable.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jcmbNomTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNbrTabletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNbrTabletteActionPerformed
       
    }//GEN-LAST:event_jNbrTabletteActionPerformed

    private void jBtnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjouterActionPerformed
        String nomTablette = (String) jcmbNomTable.getText();
        String refference = jtxtRef.getText();
        String dose = jtxtDose.getText();
        String lot = jtxtLot.getText();
        String dateFarbric = jtxtIssueDate.getText();
        String dateExp = jtxtDateExp.getText();
        String doseJour = jtxtDoseDay.getText();
        String effetSecondaire = jtxtpossibleSideEffets.getText();
        String infoCompl = jtxtCompInfo.getText();
        String conseilStockage = jtxtStrorageAdvice.getText();
        String notice = jtxtNotice.getText();
        String nombreTablette = jNbrTablette.getText();
        
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into medicament values('"+nomTablette+"', '"+refference+"', '"+dose+"', '"+lot+"',"
                    + " '"+dateFarbric+"', '"+dateExp+"', '"+doseJour+"', '"+effetSecondaire+"', '"+infoCompl+"', '"+conseilStockage+"', '"+notice+"', '"+nombreTablette+"')");
            JOptionPane.showMessageDialog(null, "Medicament ajouté avec succée!!");
            setVisible(true);
            AfficherTableaux();
            
        }
        catch(Exception e){ 
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jBtnAjouterActionPerformed

    private void jBtnAjouterComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnAjouterComponentShown

    }//GEN-LAST:event_jBtnAjouterComponentShown

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
     
    }//GEN-LAST:event_jTable1ComponentShown

    private void jBtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModifierActionPerformed
        // Modification
        
        String nomTablette = (String) jcmbNomTable.getText();
        String refference = jtxtRef.getText();
        String dose = jtxtDose.getText();
        String lot = jtxtLot.getText();
        String dateFarbric = jtxtIssueDate.getText();
        String dateExp = jtxtDateExp.getText();
        String doseJour = jtxtDoseDay.getText();
        String effetSecondaire = jtxtpossibleSideEffets.getText();
        String infoCompl = jtxtCompInfo.getText();
        String conseilStockage = jtxtStrorageAdvice.getText();
        String notice = jtxtNotice.getText();
        String nombreTablette = jNbrTablette.getText();
        
 
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("update medicament set refference='"+refference+"', dose='"+dose+"', lot='"+lot+"', dateFarbric='"+dateFarbric+"', "
                    + "dateExp='"+dateExp+"', doseJour='"+doseJour+"', effetSecondaire='"+effetSecondaire+"', infoCompl='"+infoCompl+"', conseilStockage='"+conseilStockage+"', "
                            + "notice='"+notice+"', nombreTablette='"+nombreTablette+"' where nomTablette='"+nomTablette+"' ");
            JOptionPane.showMessageDialog(null, "Les données sont modifiées avec succé !!");
            setVisible(false);
            new Pharmacie().setVisible(true);
            AfficherTableaux();
            
        }
        catch(Exception e){ 
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jBtnModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Affichage de la ligne du tableau au niveau des input
        DefaultTableModel enreTable = (DefaultTableModel)jTable1.getModel();
        int selectLigne = jTable1.getSelectedRow();
        jcmbNomTable.setText(enreTable.getValueAt(selectLigne, 0).toString());
        jtxtRef.setText(enreTable.getValueAt(selectLigne, 1).toString());
        jtxtDose.setText(enreTable.getValueAt(selectLigne, 2).toString());
        jtxtLot.setText(enreTable.getValueAt(selectLigne, 3).toString());
        jtxtIssueDate.setText(enreTable.getValueAt(selectLigne, 4).toString());
        jtxtDateExp.setText(enreTable.getValueAt(selectLigne, 5).toString());
        jtxtDoseDay.setText(enreTable.getValueAt(selectLigne, 6).toString());
        jtxtpossibleSideEffets.setText(enreTable.getValueAt(selectLigne, 7).toString());
        jtxtCompInfo.setText(enreTable.getValueAt(selectLigne, 8).toString());
        jtxtStrorageAdvice.setText(enreTable.getValueAt(selectLigne, 9).toString());
        jtxtNotice.setText(enreTable.getValueAt(selectLigne, 10).toString());
        jNbrTablette.setText(enreTable.getValueAt(selectLigne, 11).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBtnSuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSuprimerActionPerformed
        // Supression de Medicament 
        String nomTablette = (String) jcmbNomTable.getText();
        
        
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("DELETE FROM medicament WHERE nomTablette='"+nomTablette+"'");
            JOptionPane.showMessageDialog(null, "Suppression réussi avec succé !!");
            setVisible(false);
            new Pharmacie().setVisible(true);
            AfficherTableaux();
            
        }
        catch(Exception e){ 
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jBtnSuprimerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public void updateDB(){
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.prepareStatement("select from medicament");
            st.executeUpdate(" ");
            JOptionPane.showMessageDialog(null, "Les données sont modifiées avec succé !!");
            setVisible(false);
            new Pharmacie().setVisible(true);
        }
        catch(Exception e){ 
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAjouter;
    private javax.swing.JButton jBtnModifier;
    private javax.swing.JButton jBtnSuprimer;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNbrTablette;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jcmbNomTable;
    private javax.swing.JTextField jtxtCompInfo;
    private javax.swing.JTextField jtxtDateExp;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDoseDay;
    private javax.swing.JLabel jtxtDoseJour;
    private javax.swing.JTextField jtxtIssueDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNotice;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStrorageAdvice;
    private javax.swing.JTextField jtxtpossibleSideEffets;
    // End of variables declaration//GEN-END:variables
}
